local options = {
	termguicolors = true,
	guicursor = "",
	cursorline = true,
	cursorlineopt = "both",
	completeopt = "menu,menuone,noselect",
	scrolloff = 8,
	sidescrolloff = 20,
	wrap = false,
	cmdheight = 0,
	laststatus = 3,
	background = "dark",
	-- list = true,
	fillchars = { eob = " " },
	number = true,
	numberwidth = 2,
	relativenumber = true,
	ruler = false,
	expandtab = true,
	shiftwidth = 2,
	smartindent = true,
	tabstop = 2,
	softtabstop = 2,
	ignorecase = true,
	smartcase = true,
	mouse = "a",
	clipboard = "unnamedplus",
	splitbelow = true,
	splitright = true,
	swapfile = false,
	backup = false,
	undodir = os.getenv("HOME") .. "/.vim/undodir",
	undofile = true,
	hlsearch = false,
	incsearch = true,
	signcolumn = "yes",
	updatetime = 100,
	timeoutlen = 200,
}
for k, v in pairs(options) do
	vim.opt[k] = v
end
vim.opt.shortmess:append("sI")
vim.opt.isfname:append("@-@")
vim.opt.whichwrap:append("<>[]hl")
